### ISSUE TITLE
No screamers from hordes filling up maxcap. Leave room for screamers

### ISSUE THREAD

**Issue by itskat3** [FilUnderscore/ImprovedHordes#13]
Please implement a small change in the script that leaves a slot in the zombie cap for a screamer to spawn or something because I never get screamers do to having maxed out zombies from increased wandering hordes.

**Comment by FilUnderscore** [comment]
> I never get screamers do to having maxed out zombies from increased wandering hordes.

Screamers don't spawn in the wild in the current version (disabled vanilla screamers) but I've been thinking of a way to re-integrate them to appear more often due to heat while retaining their horde attracting abilities. I'll keep you updated on this topic. You should still be getting them spawning in towns.

> Please implement a small change in the script that leaves a slot in the zombie cap

This is a good idea, might make it percentage based off the MaxSpawnedZombies that you can adjust (i.e. % of MaxSpawnedZombies).

**Comment by FilUnderscore** [comment]
> Please implement a small change in the script that leaves a slot in the zombie cap

This has been implemented now in latest beta version 2.0.0-beta.2 as the following (from changelog):
> * max_spawn_capacity_percent setting to cap the number of horde entities active in the world as a percentage of MaxSpawnedZombies/MaxSpawnedAnimals game prefs (default is 0.8 or 80%). 

I'm still considering how screamers should behave outside of towns when spawned in the wild, so expect them to receive an update in the next release.

**Comment by FilUnderscore** [comment]
An update regarding this issue: Vanilla screamer spawns have been temporarily re-enabled in version 2.0.0-beta.5 until the new wilderness screamer spawn system is integrated in a future update. The city/town screamer spawns will still be present alongside this change.
