### ISSUE TITLE
Is IH still in dev for a21?

### ISSUE THREAD

**Issue by YakovAU** [FilUnderscore/ImprovedHordes#27]
Pretty keen on this mod. used in RH and likely to be used in our overhaul as well. produces very nice hordes

**Comment by FilUnderscore** [comment]
Yes it's still being actively maintained, been a bit busier than usual last few months so I've had few moments of free time to work on it. Hoping to get the release candidate out by next week which features a few minor AI changes and bug fixes - there's still one bug #24 that I'm looking at.

**Comment by YakovAU** [comment]
Good stuff mate. love the mod. It's doing nicely in Ravenhearst

**Comment by FilUnderscore** [comment]
Just an update - 2.0.0 has gone stable with a couple of bug fixes (#23 included). Still looking at #24 in the meantime and planning out future updates that will slightly improve the horde AI.

I'll be closing this issue since it isn't really a bug report and the question has already been answered, but feel free to re-open it at any time if something pops up related to it.
