### ISSUE TITLE
Request: Ability to toggle the mod

### ISSUE THREAD

**Issue by YakovAU** [FilUnderscore/ImprovedHordes#36]
For ravenhearst we have a few game options, and mixed with our biome code and IH the spawns can be intensive for some players. for the more hardcore crowd I want to add a menu option for improved hordes to be on or off.
Is it possible to have this functionality added, if you're too busy i could do a merge request and do it perhaps if you're keen.

**Comment by FilUnderscore** [comment]
It would be possible, but I think it would be better implementation-wise if this functionality was included in Ravenhearst as an additional mod (loading after IH perhaps?) that exposes the menu option which could interface with IH (through bindings or the likes, the extra mod would probably need to have a DLL with a UI class to check this) to set a bool in the DLL whether IH should run or not.

I say this mainly because outside of Ravenhearst, most people download and install IH because they want to run IH, not use it as an additional thing that can be enabled/disabled. I feel that the solution I've mentioned would be a reasonable compromise and would be of a similar effort to including it as a base functionality of the mod.

Let me know your thoughts on this. 

If you choose to make a PR for the interfacing functionality, can probably stick the bool check in [ImprovedHordesMod.CanInitializeCore()](https://github.com/FilUnderscore/ImprovedHordes/blob/8dddb7c4fedec0cda3257a965210af5d36bdc53c/Source/ImprovedHordes/ImprovedHordesMod.cs#L132) which checks a internal global bool value. You'd need to set this bool value elsewhere though, probably by exposing a public method in the same class that can be accessed from another DLL mod using [ImprovedHordesMod.TryGetInstance(Mod, out ImprovedHordesMod)](https://github.com/FilUnderscore/ImprovedHordes/blob/8dddb7c4fedec0cda3257a965210af5d36bdc53c/Source/ImprovedHordes/ImprovedHordesMod.cs#L83).

**Comment by FilUnderscore** [comment]
You could also look at scaling the horde XML configs as well if most players are finding it intensive, however there is no way to currently scale this with a setting. I might consider implementing a feature where the gamestage and entity count values in the hordes.xml file can be scaled by a multiplier as a setting in the settings XML file - this could also be exposed via the menu option as a sort of difficulty slider (or even as part of base game difficulty?).

The use case for this could be players that want to use IH but find trying to make the gameplay experience easier/harder by modifying the XML values tedious.

**Comment by YakovAU** [comment]
i did this instead, just had our code rename the modinfo file. probably easier lol. thank you 
![image](https://github.com/user-attachments/assets/e0762e26-ef8d-4a07-8de9-0186f060b7d4)
