### ISSUE TITLE
Additional config options

### ISSUE THREAD

**Issue by trevorjd** [FilUnderscore/ImprovedHordes#5]
Hi,

While doing testing tonight, I force-levelled myself to 200 and I got a basic screamer alert working, triggering on the "trying to summon horde for" text in the log. I noticed that my hordes were all Radiated and the screamer would usually be on top of me before the alert came through. Do you think that's because they're running extremely fast or do Improved Hordes spawn closer than vanilla?

In looking at the configs, I didn't spot anything to set the range at which the horde spawns. I think it would be nice to have the spawn range configurable.

Another nice-to-have would be the ability to disable the modded scout/screamer functionality. I'm sure there will be some servers that would like to use the modded wandering but keep the vanilla scouts.

**Comment by FilUnderscore** [comment]
> I noticed that my hordes were all Radiated and the screamer would usually be on top of me before the alert came through. Do you think that's because they're running extremely fast or do Improved Hordes spawn closer than vanilla?

Perhaps they spawn closer than vanilla, but that is due to the fact that if they spawn too far then the AI stops working properly and they end up in an idle animation where they spawned until you get very close to them. I've been looking into this for a while but I think it's something to do with zombies being spawned in unloaded chunks. It is also because they do run quite a bit faster since they are radiated compared to standard zombies.

> In looking at the configs, I didn't spot anything to set the range at which the horde spawns. I think it would be nice to have the spawn range configurable.

Range is configurable by changing the [chunk radius](https://github.com/FilUnderscore/ImprovedHordes/wiki/Settings#chunk_radius) setting. The distance they spawn in blocks is 16 times the chunk radius, e.g. `chunk_radius=4, spawn_distance=64`.

> Another nice-to-have would be the ability to disable the modded scout/screamer functionality. I'm sure there will be some servers that would like to use the modded wandering but keep the vanilla scouts.

Good recommendation, expect something like this in the next patch as a setting.

**Comment by trevorjd** [comment]
One of the clever people on our server suggested that the summoning message happens when the scout screams, which means she's already close, thus explaining why it feels she's so close. Why didn't I realise that? :)

**Comment by 200779b** [comment]
Can you please take a look at https://github.com/FilUnderscore/ImprovedHordes/issues/6 ?

**Comment by FilUnderscore** [comment]
ImprovedHordes 1.0.3
- Added: Option to disable custom scout hordes and use default vanilla scout hordes instead. This setting can be changed in the `settings.xml` file.
