### ISSUE TITLE
Zombies spawning in bases

### ISSUE THREAD

**Issue by olebem92** [FilUnderscore/ImprovedHordes#9]
Hello,

We've been using Improved Hordes on our dedicated server that hosts an average of 20-30 players daily. The mod has been wonderful so far however, we're starting to notice zombies spawning inside of player bases.
![image](https://user-images.githubusercontent.com/36090388/224519954-c81c01a7-2d4c-4dfe-ae66-7dca6060b1e6.png)

**Comment by olebem92** [comment]
we have tested this in bases that are completely sealed off. theyre not breaking in or coming through openings.

however, most, if not all are brender'd prefab saves from LocalPrefabs using CPM

**Comment by FilUnderscore** [comment]
First, are you running the latest version of the mod (1.2.1)? If so, are these player bases that you are reporting have zombies spawning inside fully covered by land claim blocks (i.e. is each base contained within the bounds of a land claim block).

I'm not sure whether the spawning logic currently checks for land claim blocks/bedrolls too, so I'll need to check that, but the information would be helpful.

I've only had 1 report on the forum of a similar incident with zombies spawning near the boundaries of bases, however I haven't been able to get a lot of information on the issue.

**Comment by olebem92** [comment]
Land Claims confirmed are placed, not sure on bedrolls. 2 of the bases were FULLY enclosed (no doors, windows, openings).
what i think is interesting is it only happened on rendered prefabs, ones that were previously bexport'd using CPM. i'm wondering if the mod isnt recognizing the terrain has changed in a rendered prefab

i can also confirm its not just a weird single glitch. it was happening repeatedly after restarts

**Comment by FilUnderscore** [comment]
So looking at the spawning logic, it checks for bedrolls within a 2-20 block radius of the calculated spawn points. I'll have to check if that includes Land Claim Blocks as well and see if I can add a check for that. I could increase the radius, however there is a certain limit of blocks zombies can be from players before the AI refuses to path due to unloaded chunks. 

There is something in the works for unloaded zombie hordes which is set to release around the same time as A21, however I'll see if I can put in a fix in the meanwhile.

**Comment by FilUnderscore** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix hordes spawning inside bases](https://trello.com/c/VGeBsgsg/4-fix-hordes-spawning-inside-bases)

**Comment by FilUnderscore** [comment]
Hi, please reopen if this issue is still present in the A21 version. Thanks.
